### ISSUE TITLE
support for binlog-do-db/binlog-ignore-db

### ISSUE THREAD

**Issue by ElderJames** [rusuly/MySqlCdc#10]
Specify the database to subscribe to or ignore.

**Comment by rusuly** [comment]
Hi,
If I understand correctly these are MySQL server configuration file settings, not parameters passed by client

**Comment by ElderJames** [comment]
Fine, it means I can only set it in the configuration.

**Comment by rusuly** [comment]
Just googled, it seems there are also replicate-do-db/replicate-ignore-db settings

**Comment by rusuly** [comment]
There are also following settings set in slave config files:

- replicate-do-db
- replicate-ignore-db
- replicate-do-table-
- replicate-ignore-table

Although BinlogClient acts as a replication client it doesn't support such filtering features now.

**Comment by rusuly** [comment]
Hm,
that also means if you specify **binlog-do-db/binlog-ignore-db** on the master you will not be able to replicate those changes to other replicas too.

**Comment by ElderJames** [comment]
Yes, I can only use these settings for special scenarios.

**Comment by rusuly** [comment]
Closing the issue as filtering is a high-level API that I'm not going implement now
