### ISSUE TITLE
How to get the cells column name?

### ISSUE THREAD

**Issue by yang-xiaodong** [rusuly/MySqlCdc#13]
Hello,  this is a great library~

I know that the column name is not included in the raw event data, but I need using the clolumn name to get the data from cells, so I want to ask that is there some way to get the affected column names? 

Thanks.

My database is MariaDB 10.3

**Comment by rusuly** [comment]
Hello Yang,

MariaDB was branched from MySQL 5.5 which doesn't include column names in binary log.
Column names metadata was added later in MySQL 5.6 and wasn't included in MariaDB.
The only way as I see it to get column names in MariaDB is to retrieve them using SQL query like this:
`
select TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='AspNetUsers' and TABLE_SCHEMA='Identity'
order by ORDINAL_POSITION;
`

**Comment by yang-xiaodong** [comment]
Thanks for your quick reply, I got it.

Is there any plan to provide a easily API to get column names in the future versions, I think MySqlCdc
can execute the sql queries and cache it, maybe also need to update the cache when column changed, what do you think?  this is just a suggestion

**Comment by rusuly** [comment]
This is a good idea, but I think the library should be a low-level connector. I think that for high-level API with caching features there has to be a separate library that uses MySqlCdc. Different companies may have different use cases

**Comment by yang-xiaodong** [comment]
If the goal of MySqlCdc is low-level connector, I definitely agree with you~ 

Thanks again, cheers~

**Comment by rusuly** [comment]
My pleasure,
Basically, the lib serves the same purpose as [mysql-binlog-connector-java](https://github.com/shyiko/mysql-binlog-connector-java)
We should make it more flexible but high-level API should be implemented by specific companies per their needs.
Feel free to provide feedback. It feels like nobody uses the lib.

**Comment by rusuly** [comment]
This is a really reasonable question.
Maybe the lib should support it, but definitely not in v1,
In first version I'm going to include low-level things like SSL encryption, replication

**Comment by rusuly** [comment]
Looks like the feature will be supported in MariaDB 10.5 when it is released
See [binlog_row_metadata](https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#binlog_row_metadata)

**Comment by songhejia** [comment]
I really hope to have it .

> My pleasure,
> Basically, the lib serves the same purpose as [mysql-binlog-connector-java](https://github.com/shyiko/mysql-binlog-connector-java)
> We should make it more flexible but high-level API should be implemented by specific companies/libraries per their [needs](https://github.com/shyiko/mysql-binlog-connector-java/#user-content-real-world-applications).
> Feel free to provide feedback.

I really hope to have it .
