### ISSUE TITLE
MaxScale BinLog Server compatibility like maxwell discussion

### ISSUE THREAD

**Issue by wilsonliu78** [rusuly/MySqlCdc#15]
https://github.com/zendesk/maxwell/issues/545

Hi , if connect maxscale binlog-server , it failed, pls give some suggestion

options.Hostname = {binlogserver}.hostname;
                    options.Port = {binlogserver}.port;
                    options.Username = {binlogserver}.username;
                    options.Password = {binlogserver}.password;

**Comment by rusuly** [comment]
Hi @wilsonliu78, looks like some details are missing like stack trace and exception that was thrown.

I work on macOS, and MaxScale works only on Linux so unfortunately, I cannot test it locally.
I tried to use MaxScale a year ago on a VirtualBox image and realized that it had many limitations.
First, as mentioned, it works only on Linux. Secondly, it has a proprietary license (Business Source License).
I know that MaxScale has its own CDC client protocol, so you can replicate changes using JSON, Avro format without MySqlCdc.

See the [docs](https://github.com/mariadb-corporation/MaxScale/blob/2.5/Documentation/Documentation-Contents.md)
See [Change Data Capture (CDC) Protocol](https://github.com/mariadb-corporation/MaxScale/blob/2.5/Documentation/Protocols/CDC.md)
