### ISSUE TITLE
Empty VARCHAR data column value and JSON data column inner string field value is parsed as null out of MySQL binlog.

### ISSUE THREAD

**Issue by vlevitsky** [rusuly/MySqlCdc#16]
While those 2 issues have independent root cause they are quite similar in a nature:

1. VARCHAR field value assigned as "", once gets through MySQL binlog, is parsed as null.

2. JSON field type value assigned as `{ "key": "" }`, once gets through MySQL binlog, is parsed by MySqlCdc.Providers.MySql.JsonParser.Parse() as `{ "key": null }`, thus making empty JSON string interpreted as null.

The code responsible for the latter issue might be around the line: https://github.com/rusuly/MySqlCdc/blob/740192dda4df71957eb0433629682503907a31ce/src/MySqlCdc/Providers/MySql/Json/JsonParser.cs#L234

**Comment by rusuly** [comment]
Hi, thanks
Just fixed the bug and published a new version to the [nuget](https://www.nuget.org/packages/MySqlCdc/1.0.1)

**Comment by vlevitsky** [comment]
Thanks, it looks great. I might have a recommendation for introduction of the `Task<Func<Task<IBinlogEvent>>> GetEventReaderAsync(CancellationToken cancellationToken = default)` to ease integration with F# non-blocking AsyncSeq although not sure if can open PR against this repo.

**Comment by rusuly** [comment]
Hi, unfortunately I'm not familiar with F#.
I think what you mentioned is async streams (IAsyncEnumerable) introduced in C# 8/.NET Core 3.
The library targets .NET Standard 2.0 in order to support older frameworks (like .NET Framework 4.7).
I'm not sure if IAsyncEnumerable is a breaking change. I need some time to investigate but not this week.

**Comment by vlevitsky** [comment]
Considering that it might help others, I could push a feature branch for
review, if given permission to this repository.

**Comment by rusuly** [comment]
I will implement the feature, I just made some draft. It includes some additional refactoring like removing reference to System.Threading.Channels and rewriting EventStreamChannel class. I also need to upgrade the major version since it's a breaking change in terms of API

**Comment by rusuly** [comment]
Also, I'm going to use SequenceReader(introduced in netstandard 2.1).
So I hope you use .NET Core 3.0 or later (netstandard 2.1 is .NET Core 3.0+).

**Comment by vlevitsky** [comment]
Sounds great!

And here is the (C#) code snippet we have used successfully so far:

```
        /// <summary>
        /// Opens binlog connection with the server
        /// </summary>
        /// <param name="cancellationToken">Cancellation token</param>
        /// <returns>Task completed when last event is read in non-blocking mode</returns>
        public async Task<Func<Task<IBinlogEvent>>> GetEventReaderAsync(CancellationToken cancellationToken = default)
        {
            await ConnectAsync(cancellationToken);
            await AdjustStartingPosition(cancellationToken);
            await SetMasterHeartbeat(cancellationToken);
            await SetMasterBinlogChecksum(cancellationToken);
            await _databaseProvider.DumpBinlogAsync(_channel, _options, cancellationToken);

            var eventStreamReader = new EventStreamReader(_databaseProvider.Deserializer);
            var channel = new EventStreamChannel(eventStreamReader, _channel.Stream, cancellationToken);
            var timeout = _options.HeartbeatInterval.Add(TimeSpan.FromMilliseconds(TimeoutConstants.Delta));
            return async () =>
            {
              var packet = await channel.ReadPacketAsync(cancellationToken).WithTimeout(timeout, TimeoutConstants.Message);

              if (packet is IBinlogEvent binlogEvent)
              {
                  // We stop replication if client code throws an exception
                  // As a derived database may end up in an inconsistent state.
                  return binlogEvent;
              }
              else if (packet is ErrorPacket error) throw new InvalidOperationException($"Event stream error. {error}");
              else if (packet is EndOfFilePacket && !_options.Blocking) return null;
              else throw new InvalidOperationException($"Event stream unexpected error.");
            };
        }
```

to be allow the asynchronously source binlog events streamed via (F#) AsyncSeq:

```
  let! getEvents =
    BinlogClient(fun options ->
      options.Hostname <- ...
      options.Port <- ...
      options.Username <- ...
      options.Password <- ...
      options.HeartbeatInterval <- TimeSpan.FromSeconds 10.
      options.Blocking <- true
      options.Binlog <- BinlogOptions.FromGtid <| GtidSet.Parse gtidSet).GetEventReaderAsync ()
    |> Async.AwaitTask
    |> Async.map (fun er -> fun () -> er.Invoke () |> Async.AwaitTask |> Async.map toCdcEvents)

  let rec getCdcEvents () = asyncSeq {
    let! events = getEvents ()
    for e in events do yield e
    yield! getCdcEvents () }

getCdcEvents () |> AsyncSeq.iter (...)
```

**Comment by rusuly** [comment]
Do you use .NET Core 3.0+ ?

**Comment by vlevitsky** [comment]
Yes, we use NET 5.0

**Comment by rusuly** [comment]
Ok,
I'm implementing v2 that uses Async Streams. This is the correct way in .NET Core. For example see the [PostgreSQL](https://www.npgsql.org/doc/replication.html) example.
You will need to use the IAsyncEnumerable from F#.
They say there is FSharp.Control.AsyncSeq lib

**Comment by rusuly** [comment]
I published async streams and some improvements to the [nuget](https://www.nuget.org/packages/MySqlCdc/)

**Comment by vlevitsky** [comment]
Excellent, I will check it out over the weekend.
