### ISSUE TITLE
[Question] TableMapEvent.TableMetaData.ColumnNames returns null

### ISSUE THREAD

**Issue by weirdyang** [rusuly/MySqlCdc#20]
Any hint on what could be the issue?

![image](https://user-images.githubusercontent.com/25576022/118374075-c495e800-b5ec-11eb-85a1-e831a0fb6e6e.png)

![image](https://user-images.githubusercontent.com/25576022/118374077-cbbcf600-b5ec-11eb-8bc0-6f4dd98fdb7f.png)

I'm using MySQL 8.0.23

```
þbin `   y   }     8.0.23                                             ` 
         a       


** 4 
(Î~
¨ `#      œ   €         ]Ùy9 `"   O   ë                                             ê
‡"bÂüh—8 ¶N9 `   K   6                     E    std! ! ÿ ÿ test BEGINÿ¾b9 `   K     € 3INSERT INTO test (id, name)
   VALUES
   ( 1, 3 )×ãd9 `   :   »    X      test test È   üÿ I`« 9 `   *   å    X       ÿ    3—õW9 `          -       nõ_;~ `"   O   S                                           ¾´örbÂüx—8 e+§o~ `   K   ž                     E    std! ! ÿ ÿ test BEGINÍÓ±£~ `   T   ò  € <INSERT INTO test (id, name)
   VALUES
   ( 1, "asdasdas" )‡20Ë~ `   :   ,    X      test test È   üÿ !œüc~ `   1   ]    X       ÿ    asdasdasjÕŸ;~ `      |    s       rË×=­ `"   O   Ë                                           ‡5¼ubÂüx—8 Õsh5­ `   K                        E    std! ! ÿ ÿ test BEGIN0GKð­ `   T   j  € <INSERT INTO test (id, name)
   VALUES
   ( 1, "asdasdas" )BÛtô­ `   :   ¤    X      test test È   üÿ Cî©­­ `   1   Õ    X       ÿ    asdasdas“@Öî­ `      ô    v       rOi½ `"   O   C                                           ¹|´vbÂüw—8 bV!)½ `   K   Ž                     E    std! ! ÿ ÿ test BEGIN¶¾f½ `   U   ã  € =INSERT INTO test (id, name)
   VALUES
   ( 3333, "asdasd" )öø½ `   :       X      test test È   üÿ jÙm¢½ `   /   L    X       ÿ 
  asdasdÈßØt½ `      k    w       Š6Ì(Â `"   O   º                                           wbÂüw—8 ËÔw¸Â `   K                        E    std! ! ÿ ÿ test BEGIN>ÝM¶Â `   U   Z  € =INSERT INTO test (id, name)
   VALUES
   ( 3333, "asdasd" )¸«ZÂ `   :   ”    X      test test È   üÿ \Œ<Â `   /   Ã    X       ÿ 
  asdasdüL¢Â `      â    y       y+œÃ `"   O   1                                           þWwbÂüw—8 ¶c”µÃ `   K   |                     E    std! ! ÿ ÿ test BEGINAWËÃ `   U   Ñ  € =INSERT INTO test (id, name)
   VALUES
   ( 3333, "asdasd" )üjŒäÃ `   :   	    X      test test È   üÿ û‚E*Ã `   /   :	    X       ÿ 
  asdasdèlÔÃ `      Y	    z       Ð«äà
```

Contents of my binlog.. could it be an encoding issue?

**Comment by weirdyang** [comment]
fixed it by including `binlog_row_metadata = full` in my.cnf.

but now I'm getting `Table metadata type 12 is not supported`

**Comment by rusuly** [comment]
Hi,
I believe you need to configure
`binlog_row_metadata = full`

**Comment by weirdyang** [comment]
> Hi,
> I believe you need to configure
> `binlog_row_metadata = full`

thanks I did  that, wrongly assumed v8 didn't need it. 

are you able to help me with this exception? `Table metadata type 12 is not supported`

**Comment by rusuly** [comment]
Hi, just looking at the release notes for different MySQL 8 versions.
The library handles 11 metadata [types](https://github.com/rusuly/MySqlCdc/blob/b2f0a0b792119abe10d5000d1665659572dfdd72/src/MySqlCdc/Metadata/TableMetadata.cs#L85) and it looks like a new metadata type with id=12 was added in some MySQL 8.0.x version but I don't see it in the [docs](https://dev.mysql.com/doc/dev/mysql-server/latest/classbinary__log_1_1Table__map__event.html)

You can download the source code and comment the line that throws the exception

**Comment by rusuly** [comment]
Ok, I found that the [COLUMN_VISIBILITY](https://github.com/mysql/mysql-server/blob/3e90d07c3578e4da39dc1bce73559bbdf655c28c/libbinlogevents/src/rows_event.cpp#L374) was added

**Comment by rusuly** [comment]
Just fixed it and published a new version to the nuget

**Comment by weirdyang** [comment]
that was really fast! thanks. I had cloned the repo and commented it out earlier. Much appreciated!
