### ISSUE TITLE
update row event,but  ColumnsPresentBeforeUpdate and ColumnsPresentAfterUpdate is same ?

### ISSUE THREAD

**Issue by kesshei** [rusuly/MySqlCdc#21]
1 rows were updated
{
  "TableId": 271,
  "Flags": 1,
  "ColumnsNumber": 3,
  "ColumnsPresentBeforeUpdate": [
    true,
    true,
    true
  ],
  "ColumnsPresentAfterUpdate": [
    true,
    true,
    true
  ],
  "Rows": [
    {
      "BeforeUpdate": {
        "Cells": [
          2,
          "data1",
          18
        ]
      },
      "AfterUpdate": {
        "Cells": [
          2,
          "data1",
          19
        ]
      }
    }
  ],
  "Header": {
    "Timestamp": 1627033235,
    "EventType": "MYSQL_UPDATE_ROWS_EVENT_V2",
    "ServerId": 1,
    "EventLength": 78,
    "NextEventPosition": 12237,
    "EventFlags": 0
  }
}

**Comment by rusuly** [comment]
Hi, I don't think it's the same.
Before update you have the following data [2,"data1", **18**] and after update you have [2,"data1", **19**]

**Comment by rusuly** [comment]
You can also control this behavior by tuning the **binlog_row_image** attribute in the config file.

`binlog_row_image=full` logs all columns which is default

`binlog_row_image=minimal` logs only changed columns
