### ISSUE TITLE
can't find TableId from INFORMATION_SCHEMA.TABLES.

### ISSUE THREAD

**Issue by supersdar** [rusuly/MySqlCdc#30]
hi,How to use TableId to find the corresponding table name?

**Comment by rusuly** [comment]
Hi, it looks like `INFORMATION_SCHEMA.TABLES` is a view and doesn't have table_id.
Instead, try querying `INFORMATION_SCHEMA.INNODB_TABLES` table like:

`SELECT * FROM INFORMATION_SCHEMA.INNODB_TABLES WHERE TABLE_ID = 100`

**Comment by rusuly** [comment]
Also `TableName` with `TableId` is included in the `TableMapEvent` event that precedes any `WriteRowsEvent`, `UpdateRowsEvent` or `DeleteRowsEvent` events.
