### ISSUE TITLE
Support Event To Detect Column Changes For Mysql:5.7

### ISSUE THREAD

**Issue by vinh3c** [rusuly/MySqlCdc#31]
Hi @rusuly 

We use mysql 5.7

TableMetadata.ColumnNames = null ( just on mysql:8 )

And we have to query

```select TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='AspNetUsers' and TABLE_SCHEMA='Identity'
order by ORDINAL_POSITION;
```
But we don't know when columns change in runtime to requery

Thanks

**Comment by rusuly** [comment]
Hi,
I believe [QueryEvent](https://github.com/rusuly/MySqlCdc/blob/main/src/MySqlCdc/Events/QueryEvent.cs) is written in binary log when DDL(alter table) operations are executed.
You can try and see if this event logs necessary information

**Comment by vinh3c** [comment]
I known that, QueryEvent come after Unknow Event. But i think it better when we have native event for that
Thanks rusuly.

**Comment by rusuly** [comment]
This lib is low level so parsing sql statements seems out of scope for the lib.
Also, unfortunately, currently I don't have time to support such high level abstractions

**Comment by vinh3c** [comment]
Thanks @rusuly

**Comment by rusuly** [comment]
I think the event you are looking for is 
[RowsQueryEvent](https://github.com/rusuly/MySqlCdc/blob/main/src/MySqlCdc/Events/RowsQueryEvent.cs)
See the docs for the repository on how to enable this event for MySQL or MariaDB


4.Optionally you can enable logging SQL queries that precede row based events and listen to RowsQueryEvent.

for MySQL:
binlog_rows_query_log_events = on

for MariaDB:
binlog_annotate_row_events = on

**Comment by vinh3c** [comment]
<img width="721" alt="image" src="https://github.com/rusuly/MySqlCdc/assets/111959633/c4201995-33e7-497d-ab09-d5fed58f13d1">

<img width="670" alt="image" src="https://github.com/rusuly/MySqlCdc/assets/111959633/5c7c3dcf-c023-4eb7-9d52-51026f2ce7d9">

I'm trying with that. I work for me
Thanks @rusuly

**Comment by rusuly** [comment]
Ok, just be informed that QueryEvent and RowsQueryEvent are two different events. The first is used when statement-based replication is enabled. RowsQueryEvent is used when row-based replication is used and it requires some configuration in the config file
