### ISSUE TITLE
use  Production Environment

### ISSUE THREAD

**Issue by mingyangzhu** [rusuly/MySqlCdc#9]
hi @rusuly  this lib can use Production Environment？ This is exactly the library I want.  tks.

**Comment by rusuly** [comment]
Hi,
Do you mean if it's production-ready?
Well, it's in preview but it seems to be stable.
I need more feedback and some improvements to release production-ready version

**Comment by mingyangzhu** [comment]
ok ,thanks  ,i will use it for projects.  this lib is great!!

**Comment by ElderJames** [comment]
I'm also working on development for production environments

**Comment by rusuly** [comment]
Sure, thank you guys for taking part.
I will see what I can do to finish 1.0.0 sooner.
I think the following tasks need to be done before the lib can be considered 1.0.0
1. Implement GtidSet
2. Cover at least core classes with unit tests
3. Implement reconnecting or just replace `ReplicateAsync` with `ReadEventAsync`

**Comment by rusuly** [comment]
I created an [issue](https://github.com/rusuly/MySqlCdc/issues/8) where I want people to share their thoughts on how to polish API before 1.0 released
